[package]
name = "ryaml"
version = "0.4.0"
edition = "2018"
authors = ["Ethan Smith <ethan@ethanhs.me>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ryaml"
crate-type = ["cdylib", "rlib"]

[features]
abi3 = ["pyo3/abi3-py37"]

[dependencies]
serde-saphyr = "0.0.7"
serde = { version = "1.0.228"}
pythonize = "0.26.0"
pyo3-file = "0.14.0"
serde-transcode = "1.1.1"

[dependencies.pyo3]
version = "0.26.0"
features = ["extension-module"]
